// <auto-generated />
using System;
using Mediatheque.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mediatheque.Data.Migrations
{
    [DbContext(typeof(MediathequeContext))]
    [Migration("20260127210559_FixCategorieLink")]
    partial class FixCategorieLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Mediatheque.Data.CategorieActivite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CouleurHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouleurHex = "#FF5733",
                            Nom = "Musculation"
                        },
                        new
                        {
                            Id = 2,
                            CouleurHex = "#2ECC71",
                            Nom = "Cardio"
                        },
                        new
                        {
                            Id = 3,
                            CouleurHex = "#9B59B6",
                            Nom = "Yoga"
                        },
                        new
                        {
                            Id = 4,
                            CouleurHex = "#3498DB",
                            Nom = "Sport Collectif"
                        });
                });

            modelBuilder.Entity("Mediatheque.Data.Entrainement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategorieActiviteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategorieActiviteId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("TEXT");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieActiviteId");

                    b.HasIndex("CategorieActiviteId1");

                    b.ToTable("Entrainements");
                });

            modelBuilder.Entity("Mediatheque.Data.Entrainement", b =>
                {
                    b.HasOne("Mediatheque.Data.CategorieActivite", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieActiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mediatheque.Data.CategorieActivite", null)
                        .WithMany("Entrainements")
                        .HasForeignKey("CategorieActiviteId1");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Mediatheque.Data.CategorieActivite", b =>
                {
                    b.Navigation("Entrainements");
                });
#pragma warning restore 612, 618
        }
    }
}
