// <auto-generated />
using System;
using Mediatheque.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mediatheque.Data.Migrations
{
    [DbContext(typeof(MediathequeContext))]
    [Migration("20260127203039_AjoutTableCategories")]
    partial class AjoutTableCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Mediatheque.Data.CategorieActivite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CouleurHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Mediatheque.Data.Entrainement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategorieActiviteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("TEXT");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieActiviteId");

                    b.ToTable("Entrainements");
                });

            modelBuilder.Entity("Mediatheque.Data.Entrainement", b =>
                {
                    b.HasOne("Mediatheque.Data.CategorieActivite", "Categorie")
                        .WithMany("Entrainements")
                        .HasForeignKey("CategorieActiviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Mediatheque.Data.CategorieActivite", b =>
                {
                    b.Navigation("Entrainements");
                });
#pragma warning restore 612, 618
        }
    }
}
